### ISSUE TITLE
Не могу окончательно очистить корзину покупок и еще некоторые траблы.

### ISSUE THREAD

**Issue by kostiantyn-leontiev** [nailbiter/ElDrinkoPubBot#105]
![image](https://user-images.githubusercontent.com/64928737/116749188-3c6aec80-aa09-11eb-9144-f1a104f4a18a.png)
1. Не могу очистить корзину. Пытаюсь удалить "Wizen-1.5(=0,5*1+1,0*1)л;". Прохожу всю процедуру удаления, никаких ошибок не возникает. Но этот заказ не удаляется.
2. "Wizen-0.0(=0,5*0+1,0*0+1,5*0)л; Wizen-0(=)л." Система помнит историю того, что я заказывал ошибочно. Это не нужно показывать в результате выбора. Заказы с суммарным нулевым литражом выводить не надо. Их надо вычищать.
3. При вводе в командную строку вижу сообщение
_"Уп-с!  Сталось, щось не те!
Для виправлення, надішліть нам сюди @ElDrinko_Pub ваше замовлення, та цей номер помилки 1619813667.
Ми виконаємо замовлення, усунемо помилки та проінформуємо Вас коли все виправимо.
Також пропонуємо спробувати ще раз, за допомогою команди /start, у більшості випадків це спрацьовує."_
Но при нажатии на кнопки выше удалось опять выйти в меню заказа.
Скорее всего, в этом случае надо писать что-то другое или повторять реакцию "Покласти в кошик".

**Comment by nailbiter** [comment]
closed via
* ec7f57f
* a96610e
