### ISSUE TITLE
Не могу ввести телефон после ошибочного ввода. 

### ISSUE THREAD

**Issue by kostiantyn-leontiev** [nailbiter/ElDrinkoPubBot#106]
![image](https://user-images.githubusercontent.com/64928737/116750322-f2830600-aa0a-11eb-9cb4-2ea8020a303b.png)

Несколько раз ввел неправильно, после этого не могу ввести уже валидный номер. Выдает одну и ту же реплику на ошибку.
Похоже Завесил надежно. Команда /start не помогает:

![image](https://user-images.githubusercontent.com/64928737/116750726-910f6700-aa0b-11eb-91fe-fd0517aed5d5.png)

**Comment by nailbiter** [comment]
closed via f6d7126
