### ISSUE TITLE
Исправить слайд "Благодарим за заказ"

### ISSUE THREAD

**Issue by kostiantyn-leontiev** [nailbiter/ElDrinkoPubBot#14]
![image](https://user-images.githubusercontent.com/64928737/81564933-31a2ec00-93a1-11ea-80e0-98f66cc20c16.png)
На этом слайде должно быть написано:

"Дякуємо за замовлення!
Якщо у нас будуть питання ми напишемо Вам, або зателефонуємо.".

**Comment by nailbiter** [comment]
@kostiantyn-leontiev 
я не понял. где должен быть этот слайд? при переходе из какого в какое состояние?

смотри https://github.com/nailbiter/ElDrinkoPubBot/tree/staging/docs
