### ISSUE TITLE
Отредактировать описание Милк Стаута

### ISSUE THREAD

**Issue by kostiantyn-leontiev** [nailbiter/ElDrinkoPubBot#95]
Описание должно быть таким:
Мілк Статут з додаванням тертого какао та пасти обсмаженого лісового горіха. Лісовий горіх, какао, шоколадний солод та лактоза зробили неймовірний аромат "праліне". За смаком, повнотілий без надлишкової солодкості. ABV 7,0%, IBU 20, OG 18,0%

Ссылка на картинку такой:
https://lh3.googleusercontent.com/pw/ACtC-3elotGBi2rTWSqgA2OhClpdk53DU_GN-9I7SOnK0L-oNtDZg1BGeRM7I3e-vdRmDxmXp70SVECtkDIytEtzoCXLPx6vRk5cK4Amd0Jot1ihfzRVV05hkd_3lFqEUSDl1p0Wr5QBVICUK4SrEm7wxSsL=w630-h665-no?authuser=0

И цена должна быть 80 грн, но помнится это мы уже меняли.

P.S. Сделай, пжл., Базу. Чтобы я тебя не дергал с подобными вопросами.
P.P.S. Хотел поставить этой задаче Лейбл наивысшего приоритета, но не нашел как это сделать.

**Comment by nailbiter** [comment]
done
