### ISSUE TITLE
Условная проверка валидности телефона

### ISSUE THREAD

**Issue by nailbiter** [nailbiter/ElDrinkoPubBot#96]
Нам необходимо проверять условную валидность телефона. Иногда люди вводят или ввели ранее что-то типа "1", система запомнила ЭТО в резульатате получаем вот такие запросы:
Замовлення №70; 07.01.21 15:51
Покупець: @null
Замовив: Milk Stout-2(=2,0*1)л
Адреса замовлення: Бульвар Леси Украинки 4 кв 82
Номер телефону: 1
Форма сплати: Термінал
Сума до сплати 180,00 грн.

Мы приспособились их отрабатывать, но чем дальше тем сложнее.
Предлагается либо дать форму, чтобы люди вводили правильно, либо написать шаблон, например (000) 000 0000. И проверять все под него.

Ну и продумать интерфейс для исправления ранее запомненных неправильных номеров.

Пока давай обсудим как лучше.

**Comment by kostiantyn-leontiev** [comment]
Тексты пусть выглядят вот так:

Введіть номер телефону у форматі 0000000000: тільки 10 цифр, включаючи код оператора, без пробілів та іншіх знаків.

Будь ласка, номер телефону у форматі 0000000000: тільки 10 цифр, включаючи код оператора, без пробілів та іншіх знаків.

**Comment by nailbiter** [comment]
done in 76ff822
