### ISSUE TITLE
Отредактировать итоговый блок, который перед отправкой заказа

### ISSUE THREAD

**Issue by kostiantyn-leontiev** [nailbiter/ElDrinkoPubBot#97]
В этом блоке (который перед отправкой заказа), нет номера телефона:

![image](https://user-images.githubusercontent.com/64928737/104619765-e7dc7500-5696-11eb-8e1b-eb4e4e456cbc.png)

Пусть он выглядит вот так:
Ви замовили: Mariposa-0.5(=0,5*1)л
Сума до сплати 61,50 грн.
Форма сплати: Готівка
Адреса замовлення: Мы в РФ та
Телефон: 0503309473

**Comment by nailbiter** [comment]
done in 76ff822
